// DO NOT EDIT!!!
// This file is generated by ./scripts/gen_cdn_driver_checksums.sh

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 115] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.2"),
        "1e605796f25451099ff4717358fd4e8950e33aa8a68e11935ac20cd8f53c8fe9",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.3"),
        "050474c79886935db06e3e192fc901fd07a6e73d3e6932bf238ace55f2c1bbc8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.4"),
        "8ae01f121bdf5796e8af43126007649a66a4e95f8180bb064a8d3e9f67c13131",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.5"),
        "36bfced72bf0cabb4490f95013d467edf75febcb305a6720b19f18e521d5bc10",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.2"),
        "6bbf74f9fd1ab8d0555d6031cbe77f7a7787cbe57f8e0bdc86aa1aad8d6751c2",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.3"),
        "948a33cfffafa6cdd4f2c27be805fb7e63bbe4cf34b2c35e453ae4943612d00a",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.4"),
        "f8002a84a2238270a7a503942fae2065392e7440774d132d02e154fc43898a9e",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.5"),
        "5e12ceec15ab25c877645218998e10c7f5be85b8c61af21e38df84db5f247703",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.2"),
        "43ed25623625684e1e0d663f31e935893199b5cbbb1d8fc8ca3dd06fdfdddd5c",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.3"),
        "38edccb5f5faa708392ae41bc4f2802640e426d604b137f9d861d29a2d75d97e",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.4"),
        "da880571ea61c94a79483ced1767f86c1b7a2660442a033c3c3f5b5da381e9c9",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.5"),
        "025bdb36e7008d4ea0e2506dc8107b1ae01bfe93508d64e252c8b64ca551bd7f",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.2"),
        "33e3aa9f9146899d0962538de52c8f90e908ad94d22da02dcb93b8e05cf9ac94",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.3"),
        "73a5ecec1098cfe63c49a062bc8ae90d252f801452d50b15fe5f05bc7f4dd2b5",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.4"),
        "2055ea92adee1270b299e8934d1648c226bfa5faa5a58652fa85e7997cd90696",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.5"),
        "958e6b37202ea8ed50643ad881325d706871f9f61ecb7791373991ad28a6746d",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.2"),
        "f41bea58ae676ebf1ce7b73d556973dc42382051dd7d339a2054d16eb03608eb",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.3"),
        "686bff3fff5e1cc35a9f9f6025103f9dcb46e340c386b967cea714015b337768",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.4"),
        "3c8142b54d5dade4b6a0bf7973b8f300933a93c0cffa6127c1e2cbc1bd09c2ce",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.5"),
        "68d7098c61e2414a559c1775409b0352104b086726674279e02791c9bcfb0fc3",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.4"),
        "cf8df5107e40ff4615c014089e90b0f21f5b07ead8f242ff53c374778ba7bffb",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.5"),
        "09d79701b729a52854862ba34f8756ae93f1f45a8ba33dd8300194beb5adca14",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.4"),
        "907b430ca6aac75f613f72b365d7a436d46c8b7a42adbccf51b22dfbd4d885be",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.5"),
        "4b38c2b39a41c057d021e2a5f558e316bcaa9b5b1ef41468398fee51958e801b",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.4"),
        "7b4be0b85c904fcf98805f5ef3b1b6d8988cdedbe33306c71f451465cd19c5df",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.5"),
        "8f497697b5fe676f07d7a79e4539307c2e145458aafc67ad812a915bb44bbaaf",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.4"),
        "1fe82029720c5e2192c388ca10a9251e9cffdc0453798eb2f270dcbc3865a5a8",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.5"),
        "bafc65d554eb39614c9878cf66b07c11b578dec895923ca2f5b08261d8171219",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.4"),
        "21c2e0bb9cb8d42431243681bb05b4abea75f3708ca51983d0888795e18b3a94",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.5"),
        "73cce7c25c517f3b75be60c908e447d385aeab0f28a17107319a5b1763c64c02",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.18.0+dbt0.0.1"),
        "661496d8301fff3368f192ed4ccdfb0110864595b8a4555560d68784985d24ce",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.2"),
        "ef8be74d82fd90855edcc484ff210567b499d999efa7dfde9bff6e61fe0cef43",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.3"),
        "297c14a63c51f83b939aecd796bdc860e5e8183051c65330be517825b63c95c7",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.18.0+dbt0.0.1"),
        "9ff40bb5a6c6657599faaeb47ac938f21ceb572e9e8d488c08e8ffe32647d766",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.2"),
        "570387713a9788bf11c4aed7f7949d76414306c56d3984be8ed0a9a76af82b5b",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.3"),
        "6baabcf6e9ddb7c692172f2c587690c62ea3a71e6b6eb75dc66cb7af78bbd8f9",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.1"),
        "49c1ac73128734eb36719f5912e4d3c969f52d5611e3b55a6a416f0d5f7447bb",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.2"),
        "acef6dd1195d85ee05286b3b87d9863b02926f4b4a59deda84de8d625d96ff34",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.3"),
        "8f8dd23b54b6f22c233d1071f87179c2cfe0b44d18847ed749d59b315fd9e345",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.1"),
        "912b5c737963c7023891afc59b3ae47c73641197062316a83a2733e4275b85d5",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.2"),
        "872407a0cd10870cc70871f5bf6d92e5666ac6d4c83b143d8223ff0a1c1b4f47",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.3"),
        "b6021038c9100cb1f61b3c325e98a6b4308682f3332b33fbf2400aeb8628a4ab",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.1"),
        "acb8bbc8f477a072991345fe0ab0ee36b561e7668bdbf5b900189a35dd021888",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.2"),
        "ed9b97311a5da6c9a81c2675e85a2fbe73d4e9ef392da16c0ce71b70e947146b",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.3"),
        "ac016fe6a26f3758a2eb9203c45957264f4f34dc182c148b024da2cbab324a6f",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "759eaacee1ea8139f884fa258ec8a7496ae9458f66cb8029817a2978b6f651ed",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.21.0+dbt0.21.0"),
        "07afc8277fd952d956b7de7a8129b323dad9a1aea71e35e3a0d31dee6371546d",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "aa0b1da8145aa3b374dd0bd2b52cd02a8814ce3b03490aa8b5fc99178682803c",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.21.0+dbt0.21.0"),
        "cca3bb3f50a93879a346b50fb49374ced4494f65796ccd60e933c841eea3f27f",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "0650e5069c7ba4c545fc2850143109292842b117719991a7554bd35434a08bd0",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.0"),
        "279f5b9f042a7729f33c053e675f6d0c530a9ce8b88fa6965a981bd93a939df8",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "ff3cd85d65c0425eb31471f536812c333dec6ef0eb5e51d537ce607c9d2853dc",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.0"),
        "cbc2a0865bfc311663db2c2564830e4d4d260beda29baecd4371d8ce52eada5b",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "6f38377190af7320b0020c11f726e018cae0932272adba88359bf395c0f8ad94",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.0"),
        "4986f51e67888f77999525301386505f6375edcb36af4018becff374bb3f82e2",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.0"),
        "c12c7cbfc9d7819b268389e62ae2476c36ece2d8d8844705e251269922709d82",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.1"),
        "fd1cf44eaae243479706235dcd486e28e19f96542b4de0b91da9633aea4dd69e",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.2"),
        "ab2b73c667a2b977362ca03cdca9ee309c68b1659f428dee176639d9070c9c1c",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.3"),
        "ce4f16d63e73955b7609ce3658fe95a14426ff0394305c1dcff060b5e71ce398",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.4"),
        "06577fa0d7049dbac38ad50c91c13c636f188d3278a2a3abc5ba563eb83d51f2",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.0"),
        "699697f946a6e2a7d80135304600eb716f1682b20c8d43bd324e3151f0723ceb",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.1"),
        "477b3ea638297ecfb950738cd15295a72a9b42a64e07372a7a3f7cb5c7e1164a",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.2"),
        "4283d97f8adaf6066ee84b9a3efb4ce4340774f8cd77e79310272daa317e9d7f",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.3"),
        "1be66c9643987b70b3baae8e41135415c4433d92e85508bec3c0a3c6e0151978",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.4"),
        "33f49abc1eaebead97d0e3edcfdfa37fb1c92b779bcfa5fee1022bb75ce1c9d4",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.0"),
        "ec9f0288ac76864913a29be35837bdd5698a3550edbbcd315d577e67913ba567",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.1"),
        "272922a5a3e36ba73b591f5009ced1a5f67431eb3358b27c14a2382c00f6780d",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.2"),
        "0ea7538a182b73bbafd4f594f8d63aa2cd26c3c2e354c13967540f861f20ccc7",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.3"),
        "cb2538c84e6dcbad15e074a2a9907a7cab551d66c833264a5af7835a19352cbd",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.4"),
        "4044e6e1f37ef4d5696c56b7de7303f8a56d64678609f2694413baf493cf9560",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.0"),
        "7bb6e96fd397d870020cf8c363e17b4cf7b5fbdddacd4f77a2d2815544cf8b58",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.1"),
        "ae3f9a741c9a4613e24666df4cce7cfa61517b55c7d4bd64f6cf894fcfc9688c",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.2"),
        "3c853f6444cd16bb9a7600f6b6350717aac440b840df1790d3c3d138d907283f",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.3"),
        "89c1e7b6b5e860259bb382d2b6257f9c593e8f977365f82dacc17bd14defb533",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.4"),
        "5a2600f85b0f9c8d34d91d8d0ae13cab266947238f97df07efe0351b53af3af9",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.0"),
        "ac5995cd9acc93ad4ca09a42be373111c6a977d5dff29a2ef56ce6983caea9d6",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.1"),
        "65761e237d7874452a527478f6139cd85a091fb0fedcda8999009114f5eff0f8",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.2"),
        "3c802b424c2fd1ea7fb45ebd1251fbe3e65b4d53a9d61dd4da303b1d5f206506",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.3"),
        "d6cf68f50f2551e07902d43631ff01f8dd507d9592a43cf8a074ac57ef2cb9e4",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.4"),
        "566dc019803edae2b29a58dace76034a793fd2ace289a54da35438834231e388",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "5ec5adbf634fee917f4a9ffae49e5d1ff81de14e836d6418397f31af3cae2791",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "d18e39ae09ff1a94da2dc3b4af9c7ac5f135d8affe8fab930d21966c6613b234",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0+dbt0.21.1"),
        "a651b99de9f3d4987259735f9d4bd45c965edd76d46f7b8a1126e1ada07257ab",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "ac7e0aceeda89980a62e4899d6067ebd42b929c60eceb98b045945a9bcbc72c0",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "d0b94c4d28569cc95c0a07cb4218b053727ea9df13ed0ef2f55b3a920351d589",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0+dbt0.21.1"),
        "06daae1581f75f8bf4d26fed1baf880d7ef31deeb0e15b5d6e90090e447831cc",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "06ae9ce089fbb52d6501ff62fd8b22585c18e649d1c29b4fc28339f2bcd47762",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "a826655fc9b626951d08c39b174756dff99b04b10c33601f9a1feff6325aec7a",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.1"),
        "c77793e9b83963d144a250bcec207dbec598b653eed077f4fae95e59959472c0",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "3a88d8d6e2b8b46c9425f396b33ab84f370d5141fac67a69b6da1a22212bfcb3",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "a1eb2b25f4f4bf63c731fdc5d47bbca621e4bd23c6201b28d6f98ba85e400951",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.1"),
        "6833d78af651a22cd81e8e6b1a67cf5e263ff15cbf116a3292f5558f9cdad696",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "015ccddb2d1b52d210aea7e483c49042a1dbce5c6ec154a61bdd1e6079d86499",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "f73ad9a1bc6f6f418a9abb3ca54723da32f9b70e28b610d772aa796cc4d83641",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.1"),
        "4226fa0ed53848b61647f1bdf5b914bae7a033f44dc5bd84622f6d900c1f32f8",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.16"),
        "e7e2fe70774612ec990c2343d0c13f20fdc0a263feb25c10a235464cb7b48e08",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.17"),
        "57062d3d56a0356cffb7bc1f272073c78c8c7bcc1fd0c4a98c1f78e02697ece8",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0+dbt0.21.0"),
        "9ac9df79fc9496b209c2e458543957ad5ed22806bd308e5545d652364e0cc9c5",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0+dbt0.21.2"),
        "3a4080bd38c86f8653b6efc2e34665428ddd8ccb98376c10245c5800fc2cb634",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.16"),
        "f388f1c59669734113b512ba13cd49348cc501986f016231782e87ac38db4578",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.17"),
        "ad550042738216550663ff22a66a93f9ed5021fac5f06fdebdee759efcbb95a2",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0+dbt0.21.0"),
        "d0195393f0af37f240a3004fd772a8ebc5eb69277ec3af95d1a647b795f3ff9a",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0+dbt0.21.2"),
        "cf2c357a40e6c14c469bfdf6951b4deb5484c21e6a10fe68fd042509b0a31129",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.16"),
        "0908b95bc8cf00f444a1612fe6cb15d5b4096b20b09993e4f1e7236915fc9732",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.17"),
        "c542e789dd224518170339d29a4ae76f0053829537790a15a3a53049607514a9",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.0"),
        "3dee74a5363f24572d05e64485c7ae28bd3508c062a568b043d011dbc3b40182",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.2"),
        "eaf885ee6a0ad717061bef90c2ff871ae555c1678c5845d3c3c3d4394908a433",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.16"),
        "a1ce25399ba02f915287025b20a87450dc2beb0b0f031c7a2d264458c9a7d042",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.17"),
        "cdb064c80d45c3e04e4af659b6e13eb787fe5024817b8aab7e5450da97f29564",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.0"),
        "8974353c567b4effe8998d932437fd9971501fc319b3047ee97a31766f5a4833",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.2"),
        "92dc1584b404dec204e5c1f25655a676f0c5802da74a658afcad38b8baa913a6",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.16"),
        "b9aa7e69800541d61eff310a71512b3d170d00618f15d4694a1bf8054aea3a7a",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.17"),
        "2fca51443e98b8344831cae7f602cb0cc314336c71cdea307b37047ca8d2403a",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.0"),
        "298fea09238638ec6d8cc91d3a93563b9b40217a07be8b289d9fa1a21a3aa498",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.2"),
        "6c04b1144e24de78c563753e4de888207e96d9857b26e1caec9f9c1764b80c5a",
    ),
];
