// DO NOT EDIT!!!
// This file is generated by ./scripts/gen_cdn_driver_checksums.sh

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 84] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.11"),
        "131b59fb8e2593e849418bdd072da06ea9700cefb7a71402a129ad376b0752be",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.12"),
        "d2e22873ef5da8ad184e0386d6d64ed1abbba4c5b78065837c18f0bddbeed873",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.13"),
        "e56a69c23493ad10dbbde81466bcbc0dda40c19b01df9edb9599896467a1fb95",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.14"),
        "a02689da7fbe8872dc8596dff3ac58d73c88ef7938cca139538eb7c36c7e0c89",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.11"),
        "6b2893bfc247a734392dfc719f8a5bb2d670f83c51a88f79a7edd09d8e901d6a",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.12"),
        "3fb0e9afca630f1035bd70cc0241c3aea343a3b6b6838a890a3307320ab534e1",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.13"),
        "1f3cde3a11fc7edcd9cdc8653e3f92286ae14d6302d58536775e0e33b149dc0f",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.14"),
        "2715bcce930dad27aeef010051702641021d6c9fb3c4adeda7298e87ab3e2508",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.11"),
        "99818daaadd030d4ffe35b8fdf414ea536ecf2bfd4fc462b22366b6a0468567b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.12"),
        "5de1fe4ca97bdc1bff68fb8a1048b0644194f533a3b5fe2eafa7cca793a2b0b3",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.13"),
        "c78b4513375c76702195441cee436ab629d22d7b5ef9b738ca6cc7a3d1f7e0db",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.14"),
        "a5bd27f8708a65ee6a24f5769671a65cdf91563d383504f469b524d883820ccd",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.11"),
        "8177e2d67530748ea9b269740e97cc39c516326e036a7aa499dc9f26a6e16b12",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.12"),
        "de1b8b35ca7660e8da64518babd1578556fba76633d69f2d4ad6a931f50bc8c8",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.13"),
        "451119f9a45c78eab00a2947081bb88b419641760bb59eb944a815a4ddb8709e",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.14"),
        "1bc8e6db4eef9445155dcb695434ee5092fa02f773881bbb5ecfb539baf6109c",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.11"),
        "505f4eb0a5506c4df7b64f79b711434bba9f3008bce77f0a334fed99d59e531b",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.12"),
        "4831f5658ade8d08c9c9b5465b7b943388e0e68fd2aa597e6a0b3b38dbf04200",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.13"),
        "6efeb08476b1d577dfacb82615cfcc1fb758b3b5843f9cc37163b5b7cff52130",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.14"),
        "401e60e9ff943f1b28dba850179f6c30fd1a6b704887a91bef26036102a32339",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "3e21c4c8f547c99bc97751b46654cffa0a2be4d2522af8428ea02ea4b1ed6146",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.5"),
        "76aa60a979bb141dff6af4ecdf6881b7c341d02364552d2274e954add5f52cb8",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.6"),
        "747891eaeef3d058a2829aafc3b69ef3f4d07f9998ebe56b3add4d5041b7c6e9",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "bcb45c92249b6fc57a7dc98259f2d5d18016466e820f1a423212bc919316cc5b",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.5"),
        "2c420960835c8ed7e792937f01022213ca07a975e2c1a0a5b0ad7ad7f8e37851",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.6"),
        "ff2dedef48b7fade19c403635354436c39c352ae8549fbfa7cdc3953ff86bcdd",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "cc1e2112a2571c77924602829963055d1b7ae64df16bd827a177bc7ecb6cbe55",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.5"),
        "83fdc2dc6dd1f821a6a1975ff27fd73cd0b8a43d15ab2a43f874d044e7590dd9",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.6"),
        "158a093844214dab63bf4ac3e1eb3ceba6956a7bb87265ff6874d4f26d11f023",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "7fdd7616dfbbc114e0f57fa3c7abe5a2d312562678e295bdc44a5c308c7952ed",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.5"),
        "bb9a5773f5ae12f2bf46e113dc9f559e182b0833fe0e9174356ed8145e529996",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.6"),
        "a2ad1eda57b708ead1843dd1e07dea10639f90e478dad058dbe1dd11eea0265b",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "934e8eef44da53431bb7bd7539a0049de83f5254e5db9567ceee327c4acb01c0",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.5"),
        "2e55c582a0de81b17f2d5fbd3ddf373e2c404b51c4a7ef6bf9c522b0591c4f66",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.6"),
        "ed516f0aedde04c97f079628a18ca3c1a683c18c3ffc218a5faca511c2e27c05",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.17.0+dbt0.0.1"),
        "6f1e25c0a4da44697bb449091ebd14575a92bd27e48cce49fdd56d0a7ad5066a",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.2"),
        "fb3a52e89163a61e09f5d85d03cd8d7afaaae697617e2b981128f375faa53aeb",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "759eaacee1ea8139f884fa258ec8a7496ae9458f66cb8029817a2978b6f651ed",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.17.0+dbt0.0.1"),
        "40f6627b9ecabc659c9750c06a8d836b86e807044bea150e74ac4550ac641cbf",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.2"),
        "da4087189a70deba7040d7f00faea221b492d00855d9d8eff56787eb5fbf02c1",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "aa0b1da8145aa3b374dd0bd2b52cd02a8814ce3b03490aa8b5fc99178682803c",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.2"),
        "0f3989966d5308b172d5b4cdb8d4cde6752c10ae175a1200f738a0f73c45edde",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "0650e5069c7ba4c545fc2850143109292842b117719991a7554bd35434a08bd0",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.17.0+dbt0.0.1"),
        "ddeaafefdd79dfddc38c48a405b6789e6f51985b32be163a322eaadb55d9ca30",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.2"),
        "a14e9532dc54371698c9730d7904f03431137c2c216b22ac623e84552b7cc93e",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "ff3cd85d65c0425eb31471f536812c333dec6ef0eb5e51d537ce607c9d2853dc",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.17.0+dbt0.0.1"),
        "cff84d5f3db4fe0efbfc64591d4005d81020261faee24c4b9b7b7211c4895fbd",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.2"),
        "b5ee9393977dff39f62d4196938a90313bea3681b1183ddb1e2f8afb92af23c8",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "6f38377190af7320b0020c11f726e018cae0932272adba88359bf395c0f8ad94",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.0"),
        "c12c7cbfc9d7819b268389e62ae2476c36ece2d8d8844705e251269922709d82",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.1"),
        "fd1cf44eaae243479706235dcd486e28e19f96542b4de0b91da9633aea4dd69e",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.0"),
        "699697f946a6e2a7d80135304600eb716f1682b20c8d43bd324e3151f0723ceb",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.1"),
        "477b3ea638297ecfb950738cd15295a72a9b42a64e07372a7a3f7cb5c7e1164a",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.0"),
        "ec9f0288ac76864913a29be35837bdd5698a3550edbbcd315d577e67913ba567",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.1"),
        "272922a5a3e36ba73b591f5009ced1a5f67431eb3358b27c14a2382c00f6780d",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.0"),
        "7bb6e96fd397d870020cf8c363e17b4cf7b5fbdddacd4f77a2d2815544cf8b58",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.1"),
        "ae3f9a741c9a4613e24666df4cce7cfa61517b55c7d4bd64f6cf894fcfc9688c",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.0"),
        "ac5995cd9acc93ad4ca09a42be373111c6a977d5dff29a2ef56ce6983caea9d6",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.1"),
        "65761e237d7874452a527478f6139cd85a091fb0fedcda8999009114f5eff0f8",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.2"),
        "7905dcdca5f7d965357b4ddff28b41ad03ed7d106c08fe3878194af6c80edb40",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "5ec5adbf634fee917f4a9ffae49e5d1ff81de14e836d6418397f31af3cae2791",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.2"),
        "c4abe3bc717d381dd9328f00737d0ec6cfcc3d3233b1edc49626685594959901",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "ac7e0aceeda89980a62e4899d6067ebd42b929c60eceb98b045945a9bcbc72c0",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.2"),
        "5c75a37b1a52d083005e7d6a055152b617332ad83ce83e79bd166e04297d8d12",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "06ae9ce089fbb52d6501ff62fd8b22585c18e649d1c29b4fc28339f2bcd47762",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.2"),
        "cfd03128ea16639b075bdf0df7d9c8686f608102befeb9588f257234a93d5b17",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "3a88d8d6e2b8b46c9425f396b33ab84f370d5141fac67a69b6da1a22212bfcb3",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.2"),
        "944b06f4348b924df96629950a17933bf479c180d7411d28cec8db1bb9d2c623",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "015ccddb2d1b52d210aea7e483c49042a1dbce5c6ec154a61bdd1e6079d86499",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.12"),
        "4902d80356258e886af07de17116b0396d7a90223c419a19a328b8704f10fb0a",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.13"),
        "96383629cb8aee83dac7a271eaea13c2fd69770f381ad038fc5966571b4b4b20",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.14"),
        "b5ce23a8899d48b20a81c81abc58b3c3501913c3a3f55ca7fd758fee7d459c42",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.12"),
        "50d045405336f07869122ab5f36738fedcff7d167dbfce1a3b91866a66f6cc55",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.13"),
        "8c3f5de7a79f512c3b63991367089b77518314249c9d9e6acc6429dd364123e4",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.14"),
        "5e20f4b82e40144f95f30a6f6bd2d762962bb35a1248f5e3e7209a623f972a4a",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.12"),
        "3857599e4e64dfe5df710e6502ab8fe6ec469b022626385b16e0919faba91f0c",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.13"),
        "5d07d710e6b2222654ae26c3e9d647644fc741064278ef946a0ff26e354561e6",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.14"),
        "a637f403c49faa5fc576075aedf89779bdb6cfead87ca869238115e3fea66066",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.12"),
        "5f5955646e5fcecb702cf1b6566510903d16d28c0689120844c1c153a18b21e1",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.13"),
        "8dcb699a885b412593422b4965984c5d99b6219a7e8a2797083de694dbb414db",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.14"),
        "fb63b52973bd926d1c48f8ddd93e8c97c21fb404b9a2341600018616dfda6240",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.12"),
        "e1b4e964d8d1f7047e4549e1a75fea08a1accbc029275698340760fc68eab237",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.13"),
        "1b5e0e064ef165613ac2d9e15569df82fe2847544de60e5184ead134964b0690",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.14"),
        "05e98a21a8aa4da26b2d34ee185003f11972bd59deaa00541faf86d0c6833a81",
    ),
];
