// DO NOT EDIT!!!
// This file is generated by ./scripts/gen_cdn_driver_checksums.sh

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 94] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.20"),
        "22b9d3596c8cbcafec0394833d173ae3e4c3a409f74bf9c09e0a191e1286e17d",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.21"),
        "55e1cac0e6e147f33ea5fe60258962eba4e47dd25031c9ce03de8f15e75f2841",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.18.0+dbt0.0.22"),
        "f6ebd9d429807722aa2c42822a0e5dc957914f91705dabd1c18113ce0aa13af3",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.20"),
        "5b7fb26fae318c9e71e7f0fa778f13db65d01fd1ff5a6754b5b5d490f3f5b2c3",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.21"),
        "264407755e0fa8aa632f004b08bf51a2ca7d99e7297805a52f95ef3fa80bd230",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.18.0+dbt0.0.22"),
        "2939d31a809456e5362be24372e00808015a8c599ff0a8d121a3012752878bb7",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.20"),
        "fe5bf4889d158e09dd18c35634f2d566903199f888d5f7a2f97e2dd5d424b177",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.21"),
        "5611a7fd46dd46ebeb9ce02e3da9ccdd5557e56bfca0c677d80cb332e3b309f0",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.22"),
        "bc0e9fc2c52681953f425a8ef154f6c9667feec16ae96be70fa8f743e17e6d73",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.20"),
        "98d57e8cddc01814c46c4af25dacca5b7e6b02266c513d29b07b5eed24a13799",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.21"),
        "bbe306bac7d3d38aa0da044a1905be9e95c1705934f869330a8f6b7ee249d07c",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.22"),
        "1ba38a1acec0cd3008fb0ec18264ed2a578dd437755f5ffccdc9a928e90999ab",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.20"),
        "8106664e2a15e2fa459b3f5f300885eb46b49614a50f134bc1af2a47c87979ea",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.21"),
        "9bf86626884e9496a11bfea94c3170c72f2da9521248b20495cf7c347e36d068",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.22"),
        "e933574b81569b072ea52411b8ff6b039aed0dea15ae9838ef83fd1e741a9fd5",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "3e21c4c8f547c99bc97751b46654cffa0a2be4d2522af8428ea02ea4b1ed6146",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.5"),
        "76aa60a979bb141dff6af4ecdf6881b7c341d02364552d2274e954add5f52cb8",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.18.0+dbt0.0.6"),
        "747891eaeef3d058a2829aafc3b69ef3f4d07f9998ebe56b3add4d5041b7c6e9",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "bcb45c92249b6fc57a7dc98259f2d5d18016466e820f1a423212bc919316cc5b",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.5"),
        "2c420960835c8ed7e792937f01022213ca07a975e2c1a0a5b0ad7ad7f8e37851",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.18.0+dbt0.0.6"),
        "ff2dedef48b7fade19c403635354436c39c352ae8549fbfa7cdc3953ff86bcdd",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "cc1e2112a2571c77924602829963055d1b7ae64df16bd827a177bc7ecb6cbe55",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.5"),
        "83fdc2dc6dd1f821a6a1975ff27fd73cd0b8a43d15ab2a43f874d044e7590dd9",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.6"),
        "158a093844214dab63bf4ac3e1eb3ceba6956a7bb87265ff6874d4f26d11f023",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "7fdd7616dfbbc114e0f57fa3c7abe5a2d312562678e295bdc44a5c308c7952ed",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.5"),
        "bb9a5773f5ae12f2bf46e113dc9f559e182b0833fe0e9174356ed8145e529996",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.6"),
        "a2ad1eda57b708ead1843dd1e07dea10639f90e478dad058dbe1dd11eea0265b",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "934e8eef44da53431bb7bd7539a0049de83f5254e5db9567ceee327c4acb01c0",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.5"),
        "2e55c582a0de81b17f2d5fbd3ddf373e2c404b51c4a7ef6bf9c522b0591c4f66",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.6"),
        "ed516f0aedde04c97f079628a18ca3c1a683c18c3ffc218a5faca511c2e27c05",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.18.0+dbt0.0.1"),
        "661496d8301fff3368f192ed4ccdfb0110864595b8a4555560d68784985d24ce",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.18.0+dbt0.0.1"),
        "9ff40bb5a6c6657599faaeb47ac938f21ceb572e9e8d488c08e8ffe32647d766",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.1"),
        "49c1ac73128734eb36719f5912e4d3c969f52d5611e3b55a6a416f0d5f7447bb",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.1"),
        "912b5c737963c7023891afc59b3ae47c73641197062316a83a2733e4275b85d5",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.1"),
        "acb8bbc8f477a072991345fe0ab0ee36b561e7668bdbf5b900189a35dd021888",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.17.0+dbt0.0.1"),
        "6f1e25c0a4da44697bb449091ebd14575a92bd27e48cce49fdd56d0a7ad5066a",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.2"),
        "fb3a52e89163a61e09f5d85d03cd8d7afaaae697617e2b981128f375faa53aeb",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "759eaacee1ea8139f884fa258ec8a7496ae9458f66cb8029817a2978b6f651ed",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.17.0+dbt0.0.1"),
        "40f6627b9ecabc659c9750c06a8d836b86e807044bea150e74ac4550ac641cbf",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.2"),
        "da4087189a70deba7040d7f00faea221b492d00855d9d8eff56787eb5fbf02c1",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "aa0b1da8145aa3b374dd0bd2b52cd02a8814ce3b03490aa8b5fc99178682803c",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.2"),
        "0f3989966d5308b172d5b4cdb8d4cde6752c10ae175a1200f738a0f73c45edde",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "0650e5069c7ba4c545fc2850143109292842b117719991a7554bd35434a08bd0",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.17.0+dbt0.0.1"),
        "ddeaafefdd79dfddc38c48a405b6789e6f51985b32be163a322eaadb55d9ca30",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.2"),
        "a14e9532dc54371698c9730d7904f03431137c2c216b22ac623e84552b7cc93e",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "ff3cd85d65c0425eb31471f536812c333dec6ef0eb5e51d537ce607c9d2853dc",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.17.0+dbt0.0.1"),
        "cff84d5f3db4fe0efbfc64591d4005d81020261faee24c4b9b7b7211c4895fbd",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.2"),
        "b5ee9393977dff39f62d4196938a90313bea3681b1183ddb1e2f8afb92af23c8",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "6f38377190af7320b0020c11f726e018cae0932272adba88359bf395c0f8ad94",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.2"),
        "ab2b73c667a2b977362ca03cdca9ee309c68b1659f428dee176639d9070c9c1c",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.3"),
        "ce4f16d63e73955b7609ce3658fe95a14426ff0394305c1dcff060b5e71ce398",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.4"),
        "06577fa0d7049dbac38ad50c91c13c636f188d3278a2a3abc5ba563eb83d51f2",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.2"),
        "4283d97f8adaf6066ee84b9a3efb4ce4340774f8cd77e79310272daa317e9d7f",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.3"),
        "1be66c9643987b70b3baae8e41135415c4433d92e85508bec3c0a3c6e0151978",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.4"),
        "33f49abc1eaebead97d0e3edcfdfa37fb1c92b779bcfa5fee1022bb75ce1c9d4",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.2"),
        "0ea7538a182b73bbafd4f594f8d63aa2cd26c3c2e354c13967540f861f20ccc7",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.3"),
        "cb2538c84e6dcbad15e074a2a9907a7cab551d66c833264a5af7835a19352cbd",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.4"),
        "4044e6e1f37ef4d5696c56b7de7303f8a56d64678609f2694413baf493cf9560",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.2"),
        "3c853f6444cd16bb9a7600f6b6350717aac440b840df1790d3c3d138d907283f",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.3"),
        "89c1e7b6b5e860259bb382d2b6257f9c593e8f977365f82dacc17bd14defb533",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.4"),
        "5a2600f85b0f9c8d34d91d8d0ae13cab266947238f97df07efe0351b53af3af9",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.2"),
        "3c802b424c2fd1ea7fb45ebd1251fbe3e65b4d53a9d61dd4da303b1d5f206506",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.3"),
        "d6cf68f50f2551e07902d43631ff01f8dd507d9592a43cf8a074ac57ef2cb9e4",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.4"),
        "566dc019803edae2b29a58dace76034a793fd2ace289a54da35438834231e388",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.2"),
        "7905dcdca5f7d965357b4ddff28b41ad03ed7d106c08fe3878194af6c80edb40",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "5ec5adbf634fee917f4a9ffae49e5d1ff81de14e836d6418397f31af3cae2791",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "d18e39ae09ff1a94da2dc3b4af9c7ac5f135d8affe8fab930d21966c6613b234",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.2"),
        "c4abe3bc717d381dd9328f00737d0ec6cfcc3d3233b1edc49626685594959901",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "ac7e0aceeda89980a62e4899d6067ebd42b929c60eceb98b045945a9bcbc72c0",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "d0b94c4d28569cc95c0a07cb4218b053727ea9df13ed0ef2f55b3a920351d589",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.2"),
        "5c75a37b1a52d083005e7d6a055152b617332ad83ce83e79bd166e04297d8d12",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "06ae9ce089fbb52d6501ff62fd8b22585c18e649d1c29b4fc28339f2bcd47762",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "a826655fc9b626951d08c39b174756dff99b04b10c33601f9a1feff6325aec7a",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.2"),
        "cfd03128ea16639b075bdf0df7d9c8686f608102befeb9588f257234a93d5b17",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "3a88d8d6e2b8b46c9425f396b33ab84f370d5141fac67a69b6da1a22212bfcb3",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "a1eb2b25f4f4bf63c731fdc5d47bbca621e4bd23c6201b28d6f98ba85e400951",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.2"),
        "944b06f4348b924df96629950a17933bf479c180d7411d28cec8db1bb9d2c623",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "015ccddb2d1b52d210aea7e483c49042a1dbce5c6ec154a61bdd1e6079d86499",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "f73ad9a1bc6f6f418a9abb3ca54723da32f9b70e28b610d772aa796cc4d83641",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.14"),
        "b5ce23a8899d48b20a81c81abc58b3c3501913c3a3f55ca7fd758fee7d459c42",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.16"),
        "e7e2fe70774612ec990c2343d0c13f20fdc0a263feb25c10a235464cb7b48e08",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.18.0+dbt0.0.17"),
        "57062d3d56a0356cffb7bc1f272073c78c8c7bcc1fd0c4a98c1f78e02697ece8",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.14"),
        "5e20f4b82e40144f95f30a6f6bd2d762962bb35a1248f5e3e7209a623f972a4a",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.16"),
        "f388f1c59669734113b512ba13cd49348cc501986f016231782e87ac38db4578",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.18.0+dbt0.0.17"),
        "ad550042738216550663ff22a66a93f9ed5021fac5f06fdebdee759efcbb95a2",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.14"),
        "a637f403c49faa5fc576075aedf89779bdb6cfead87ca869238115e3fea66066",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.16"),
        "0908b95bc8cf00f444a1612fe6cb15d5b4096b20b09993e4f1e7236915fc9732",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.17"),
        "c542e789dd224518170339d29a4ae76f0053829537790a15a3a53049607514a9",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.14"),
        "fb63b52973bd926d1c48f8ddd93e8c97c21fb404b9a2341600018616dfda6240",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.16"),
        "a1ce25399ba02f915287025b20a87450dc2beb0b0f031c7a2d264458c9a7d042",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.17"),
        "cdb064c80d45c3e04e4af659b6e13eb787fe5024817b8aab7e5450da97f29564",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.14"),
        "05e98a21a8aa4da26b2d34ee185003f11972bd59deaa00541faf86d0c6833a81",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.16"),
        "b9aa7e69800541d61eff310a71512b3d170d00618f15d4694a1bf8054aea3a7a",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.17"),
        "2fca51443e98b8344831cae7f602cb0cc314336c71cdea307b37047ca8d2403a",
    ),
];
